name: 'refactoring_module'
version: '1.0.0'
config-version: 2

profile: 'refactoring_module' # This must match your profiles.yml name

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

models:
  refactoring_module:
    staging:
      +materialized: view
    intermediate:
      +materialized: table
    marts:
      +materialized: table